version: '3.8'

networks:
  webnet:
    external: true
  bookql_internal:

volumes:
  bookql_db_data:

services:
  bookql_postgres:
    image: postgres:16.3-alpine
    restart: unless-stopped
    networks: [ bookql_internal ]
    volumes:
      - bookql_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${BOOKQL_POSTGRES_PASSWORD}
      POSTGRES_USER: ${BOOKQL_POSTGRES_USER}
      POSTGRES_DB: ${BOOKQL_POSTGRES_DB:-postgres}
    command:
      - postgres
      - "-c"
      - log_min_error_statement=ERROR
      - "-c"
      - log_min_messages=ERROR
      - "-c"
      - log_destination=stderr

  bookql_hasura:
    image: hasura/graphql-engine:v2.35.1.cli-migrations-v3
    restart: unless-stopped
    networks: [ bookql_internal, webnet ]
    depends_on:
      - bookql_postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${BOOKQL_POSTGRES_USER}:${BOOKQL_POSTGRES_PASSWORD}@bookql_postgres:5432/${BOOKQL_POSTGRES_DB:-postgres}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"  # Disable in production
      HASURA_GRAPHQL_ADMIN_SECRET: ${BOOKQL_HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    volumes:
      - ./projects/book_ql/hasura/migrations:/hasura-migrations:ro
      - ./projects/book_ql/hasura/metadata:/hasura-metadata:ro

  bookql_frontend:
    image: ${REGISTRY:-docker.io/martinvavalos}/bookql-frontend:${TAG:-main}
    restart: unless-stopped
    networks: [ webnet ]
    environment:
      VITE_GRAPHQL_URL: https://vigilantmuse.com/project/library/graphql
