networks:
  vm_webnet:
    external: true
  bookql_internal:

volumes:
  bookql_db_data:

services:
  bookql_postgres:
    image: postgres:16.3-alpine
    restart: unless-stopped
    networks: [ bookql_internal ]
    volumes:
      - bookql_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Muse1997!
      POSTGRES_USER: muse
      POSTGRES_DB: postgres
    command:
      - postgres
      - "-c"
      - log_min_error_statement=ERROR
      - "-c"
      - log_min_messages=ERROR
      - "-c"
      - log_destination=stderr

  bookql_hasura:
    image: hasura/graphql-engine:v2.35.1.cli-migrations-v3
    restart: unless-stopped
    networks: [ bookql_internal, vm_webnet ]
    depends_on:
      - bookql_postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://muse:Muse1997!@bookql_postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"  # Disable in production
      HASURA_GRAPHQL_ADMIN_SECRET: vigilantmuse
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"your-super-secret-jwt-key-min-32-chars-long-change-this-in-production"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    volumes:
      - ./hasura/migrations:/hasura-migrations:ro
      - ./hasura/metadata:/hasura-metadata:ro

  bookql_frontend:
    image: ${REGISTRY:-docker.io/martinvavalos}/bookql-frontend:${TAG:-main}
    restart: unless-stopped
    networks: [ vm_webnet ]
    environment:
      VITE_GRAPHQL_URL: https://vigilantmuse.com/projects/library/graphql
