version: 3
endpoint: http://localhost:5050
# endpoint: http://graphql-engine:5050
# endpoint: http://graphql-engine:8080/v1/graphql
admin_secret: vigilantmuse
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
